### PR TITLE
Restructuring

### PR DESCRIPTION
**Pull request by jens-t**
As discussed in #4, i began restructuring the css and the webpack build, fixed some bugs and did some other things, here is the full list:

- removed `dist` folder from repository
- former `dist` files are now in `src` and are copied to dist during build
- `ts` moved inside `src`
- sass build added
- transformed `css` to `scss` files
- moved css font declarations to `scss` folder
- added watch build to package.json

i only made structural changes so far. final css and js should work exactly as before. the `src/scss/sidebar` folder will be removed in the future, after refactoring the css. i also plan to make first small visiual changes and adjust the html generated by js & in the html folder as neccessary, and add folders for modules, components inside `src/scss` during the refactoring.

i added a watch build for more dev comfort :)

so far the `scss` doesn't differ much from the `css` the syntax is basically the same as in css, but you could use some extra helper that aren't available in css. you will see what i mean after the css refactoring.

if you feel comfortable with these changes this PR could be merged, i would add new PR's for the coming changes. (at first an example fo a different js view, to elaborate on the last question you asked in ticket #4)

### CODE REVIEW

**Comment by tim-we** [comment]
Sounds good, only thing you forgot is to copy the `manifest.json` to the `dist` folder but I fixed that.

**Comment by tim-we** [comment]
I am not sure why this is working:

```js
entry: {
	background: './src/ts/background/background.ts',
	bmSelector: './src/ts/bookmark-selector/Controller.ts',
	menu: './src/ts/browserAction/Menu.ts',
	options: './src/ts/options/OptionsPage.ts',
	sidebar: './src/ts/sidebar/sidebar.ts',
	tabSelector: './src/ts/browserAction/TabSelector.ts',
	privileged: './src/ts/extension-pages/privileged.ts',

	'bookmark-selector': './src/scss/bookmark-selector.scss',
	'menu': './src/scss/menu.scss',
	'options': './src/scss/options.scss',
	'overlay-menu': './src/scss/overlay-menu.scss',
	'privileged': './src/scss/privileged.scss',
	'tab-selector': './src/scss/tab-selector.scss',
	'sidebar': './src/scss/sidebar.scss',
	'tab-view-simple-list': './src/scss/tab-view-simple-list.scss'
}
```

I would expect double entries like `menu`, `options` and `privileged` to be overwritten by the single-quoted strings but the build process still works. Do you know why?

**Comment by tim-we** [comment]
I was referring to the double object key problem. To my understanding of Javascript this should not work. But Webpack still manages to get both entries.

**Comment by jens-t** [comment]
It is valid since es6:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#Duplicate_property_names

**Comment by tim-we** [comment]
I thought it was still working because all the JS & CSS files are being generated but it is not (try loading the extension in Firefox). I guess I was a bit quick to accept this PR, should have checked it properly.

So far I was unable to fix this. Removing the duplicates is not enough, the generated JS files still contain some evil `eval`-encapsulated code which is not allowed in web extensions. Any idea how this could be fixed?

**Comment by tim-we** [comment]
Well it was partially my fault. Disabling source maps breaks the extension because for some reason webpack decides to use `eval` in that case. I renamed the duplicates as a temporary solution.

**Comment by jens-t** [comment]
> I thought it was still working because all the JS & CSS files are being generated but it is not (try loading the extension in Firefox). I guess I was a bit quick to accept this PR, should have checked it properly.

i think that's not a big problem `typescript` is still a development branch, so we're probably the only ones noticing the problems :)

> So far I was unable to fix this. Removing the duplicates is not enough, the generated JS files still contain some evil eval-encapsulated code which is not allowed in web extensions. Any idea how this could be fixed?

there musst be an webpack option to disable this. but i'm not a webpack expert as i'm using gulp most of the time. i don't like tools that do things without asking, gulp is here more explizit then webpack. if we don't find a simple solution i could rewrite the build process with gulp. then we would have full control over the build process.

> Well it was partially my fault. Disabling source maps breaks the extension because for some reason webpack decides to use eval in that case. I renamed the duplicates as a temporary solution.

thats tricky, i remember the csp eval thing from an firefox os app i once developed. there must be a module bundler that doesn't use eval or as mentioned a webpack setting that disables that.

> For some reason that I do not understand webpack also creates .js files for the scss files.

that's probably easy to fix, with webpack, i could take a look at it this.

but these problems might be showing up in the future as well, as webpack is something thats more for spa react/vue projects. the architecture of the extension we have now is more like a website, so should i migrate the build to gulp in the longer run? what do you think?

**Comment by tim-we** [comment]
> i don't like tools that do things without asking

I could not agree more :)

> if we don't find a simple solution i could rewrite the build process with gulp. then we would have full control over the build process.

If you are familiar with gulp and think this would be better suited for the project that would be nice.
I have always had issues with webpack...

> some other thing: we should also add a prod and a dev build. and make different build tasks to access these builds.

Yes I agree. I just focused on actual development once I got webpack working, that's why there is no production build configuration.

**Comment by jens-t** [comment]
Ok, give me some time, by the end of the week at the latest, i will will make a PR with gulp instead of webpack.

with gulp we need a seperate module bundler, like browserify (in combination with babel, if we want to keep the es6 module import syntax, browserify supports only commonjs imports as far as i know). 
if that were too much buzz words, have a look here for explanations:
https://medium.com/@rukshandangalla/what-is-best-javascript-module-bundler-316b73049660

**Comment by jens-t** [comment]
gulp PR is out ...

considering the tightly coupled js & html problem:
```js
let urlInput:HTMLInputElement = <HTMLInputElement>document.getElementById("url");
```
I would advise to not generate html elements with js. I think we should use a template lib, when we need to change or create html with js. something like handlebars or simple es6 template literals. In addition to that i would recommend a special view format. And use a global event bus for view updates. with that structure we can decouple the js that is for the logic from the js that handles the views.

Normally i use something like this:
```js
var CustomView = View.extend({

  // add listener
  events: {
    'click .element': 'clickHandler'
  },

  // cache child elements
  elements: {
    '.element': 'element'
  },

  // constructor
  init: function () {

    // options
    console.log(this.options);

    // view root element
    console.log(this.$el);

    // cached child element
    console.log(this.$element);

    // emit view event
    this.emit('submit', args);
  },

  // declare custom methods & handler
  clickHandler: function (event) {
    console.log('element was clicked');
  }

});

// init view
var wrapper = new CustomView({
  el: '.wrapper'
});

// listen for view event
wrapper.on('submit', function (args) {
  console.log(args);
});

```

Maybe it's still to abstract to understand what i mean, i could transform the privileged.ts to a structure like that as an example and make a PR, so you could have a closer look ... if it is an option for you to restructure the js codebase again ...

**Pull request merged**
