### PR TITLE
build changes

### PR DESCRIPTION
**Pull request by ghost**
**changes:**
- webpack removed
- gulp added
- stylelint added

**info:**
- needs final testing
- faster builds
- except: typescript build seems very slow (is this normal?)

### CODE REVIEW

**Comment by tim-we** [comment]
The typescript build takes 23 seconds on my machine compared to 4-5 seconds with the webpack build.
Perhaps it does a lot of duplicate work like recompiling all included files again for each output file?

More important: The generated JS files do not work properly. I get the following errors when loading the extension in Firefox 64:
```
ReferenceError: regeneratorRuntime is not defined background.js:2048:1
ReferenceError: regeneratorRuntime is not defined sidebar.js:286:1 
```

The generated code seems to be targeted at ES5 with polyfills for Promises, classes, etc.
The errors above seem to be caused by some missing polyfills (I just had a quick glance at the code so I could be wrong of course).
Is it possible to avoid this? The targeted browsers (currently just Firefox 63^) support all this natively and do not require that extra compilation step.

**Comment by jens-t** [comment]
> The typescript build takes 23 seconds on my machine compared to 4-5 seconds with the webpack build.
Perhaps it does a lot of duplicate work like recompiling all included files again for each output file?

That might be it. I will check if i find a way to optimize this.

> Is it possible to avoid this? The targeted browsers (currently just Firefox 63^) support all this natively and do not require that extra compilation step.

That sounds like i have used the wrong babel preset.

**Comment by jens-t** [comment]
I think i've found a way to fix the build problems. The typescript build should also run much faster ...

**Comment by jens-t** [comment]
Here's more info according the polyfill problem:
https://stackoverflow.com/questions/28976748/regeneratorruntime-is-not-defined?answertab=active#tab-top

It seems that only the generator polyfill is needed : `babel-runtime/regenerator`

And we should possibly use Babel's runtime transformer for automating polyfill inclusion:
https://babeljs.io/docs/en/babel-runtime/

**Comment by tim-we** [comment]
Good job so far, also build times are back to normal 👍 
I do not think uglify is needed since extensions are zipped anyway (.xpi files are just .zip files), downloaded just once and the extension is not that big. Also it might cause problems with the automatic code review process from Mozilla.

I do not understand why a generator polyfill is needed as generator are [fully supported in Firefox](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*).
So if possible polyfills should be disabled completely, as Typescript is already dealing with any language features that are not in es2017.

The files are still bigger than before:
webpack vs gulp JS file size
So I assume there is still a lot of unnecessary bloat bundled with the code
Perhaps you have an idea on how to fix that.


Also the CSS references in the HTML files need to be updated (e.g. `sidebar-css.css` -> `sidebar.css`).

**Comment by jens-t** [comment]
Seems like babel's preset-env includes too many polyfills or that's the typical overhead that babel brings, when using preset-typescript.
So if typescript compiles to es2017 and that this is full supported in firefox 63, we need babel only to compile es6 imports to commonjs imports. Thats all not ideal. And combining the babel and the typescript compiler brings some other problems. Would be a lot easier and less tooling if typescript could bundle es6 modules directly :)

Maybe i will have to find a way to build the js without babel and perhaps without browserify if it only supports es6 module bundling with babel.

But first i will check if it is possible to optimize the current solution with babel. And update the css references.

**Comment by jens-t** [comment]
Ok, seems like the typescript can transform the es6 module syntax to commonjs imports. So let me check the bundle when we use the typescript compiler instead of the babel compiler.

**Comment by jens-t** [comment]
Ok, we have a winner :D

bildschirmfoto-20181125215213-1518x216

**Comment by tim-we** [comment]
I got good news for you :) We can use `tsc` directly.
I just found out that you can use JavaScript modules natively even in background scripts if we use a background page. So it is not required to bundle the code.

The project started with a single JS file that just closed all your tabs and created the bookmarks. 
That was all, no sidebar, no menu, no options. That's why I started with pure JS but by now the project grew to a size that IMO requires something like Typescript to have a sane dev experience. The TS integration in VS Code is really good. If you change something you know immediately if you break something somewhere else. TS is a must for this project, everything else is optional and may be considered too much tooling for this project.

**Comment by jens-t** [comment]
Ok, so typescript it is. I will focus only on the css then.

> requires something like Typescript to have a sane dev experience

Thats subjective, i write js since 15 years and never missed something like typescript. but as this is your project i accept that you want to go the typescript way. but i think structural problems are still there, typescript helps with type checking, but not with the code structure. let me know, if you want to know what i mean. otherwise lets just keep it this way.

We need the gulp build still for the css, so what should i do with the js gulp task now? Remove it?

**Comment by jens-t** [comment]
I started to modify the current build, like you described, in other words i remove the bundler fom the build and add gulp-typescript. Let's see if that's good enough ...

**Comment by jens-t** [comment]
Changed the build, I think it works well, i found a way to use incremental builds. Things to do:

- add gulp log messages for typescipt builds (build and watch)
- adjust the js entrypoints in the html files (src file names are now dist file names, no filename mapping as before)
- checking the tsconfig.js settings for optimization
- find a way to ignore or clean up empty files like `ts/util/Types.js`
- test module imports in firefox

**Comment by tim-we** [comment]
>adjust the js entrypoints in the html files (src file names are now dist file names, no filename mapping as before)

Also they have to be of type module for the imports statements to work:
```html
<script type="module" src="..."></script>
```

> find a way to ignore or clean up empty files like ts/util/Types.js

I think this can be done using `.d.ts` files instead of `.ts`. I'll have a look into it.

> test module imports in firefox

 I did this with a test extension.

> use background page for background script to enable js imports (@tim-we)

Just add a `background.js` file in the HTML folder with this content:
```html
<html>
	<head>
		<meta charset="utf-8">
		<script type="module" src="../js/background/background.js" ></script>
	</head>
</html>
```

**Comment by jens-t** [comment]
When running `npm run typecheck` there many `browser` namespace errors:
```bash
src/ts/util/Types.ts:39:13 - error TS2503: Cannot find namespace 'browser'
```
Was this always a problem or is this new? Is there a way to tell the tsc that this is a global?

**Comment by tim-we** [comment]
I think you forgot the webext browser type definitions:
```json
"dependencies": {
    "@types/firefox-webext-browser": "^63.0.1",
```

Sorry I forgot to mention the `manifest.json` change but I see you figured it out.

**Comment by jens-t** [comment]
I think we should have one js file per html entry located directly at the top level of the `ts` folder, that acts as init module and has the same name as the html file ...

**Comment by tim-we** [comment]
> I think we should have one js file per html entry located directly at the top level of the ts folder, that acts as init module and has the same name as the html file ...

If you prefer that go ahead, I do not mind.

**Comment by jens-t** [comment]
> If you prefer that go ahead, I do not mind.

I send you an mail to your mail adress from the ff addon page, maybe lets discuss this first per mail ... for the moment it works the way it is.

Or let me say it works almost: The imports in the ts files are without the extensions but the browser needs .js extension to find the modules. Maybe there is an option for typescript to add the .js extension ...

**Comment by jens-t** [comment]
Hmm ... maybe we should add the .js extension in the .ts files:
https://github.com/Microsoft/TypeScript/issues/18971

**Comment by tim-we** [comment]
> Hmm ... maybe we should add the .js extension in the .ts files:
> Microsoft/TypeScript#18971

If that is the easiest solution go for it. Typescript isn't always perfect, I'll give you that ;)

**Comment by jens-t** [comment]
you forgot the last commit :)

**Pull request merged**
